# Generated by Django 5.2.13 on 2026-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Studio Rossi SRL', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/')),
                ('piano', models.CharField(default='Pro', max_length=30)),
                ('posti_totali', models.PositiveIntegerField(default=8)),
                ('fuso_orario', models.CharField(default='Europe/Rome', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizzazione',
                'verbose_name_plural': 'Organizzazione',
            },
        ),
    ]
