# Generated by Django 5.2.13 on 2026-04-24 19:53

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=300)),
                ('eventi', models.JSONField(default=list, help_text='Lista di eventi (chiavi WebhookEvento). Vuoto = tutti')),
                ('secret', models.CharField(blank=True, help_text='Se impostato, il body viene firmato (HMAC-SHA256) → header X-CRM-Signature', max_length=64)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultimo_tentativo_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_status', models.PositiveIntegerField(blank=True, null=True)),
                ('ultimo_errore', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Etichetta per riconoscere il token', max_length=80)),
                ('token', models.CharField(default=api.models._make_token, editable=False, max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API token',
                'ordering': ['-created_at'],
            },
        ),
    ]
