# Generated by Django 5.2.13 on 2026-04-24 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('opportunita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('call', 'Chiamata'), ('email', 'Email'), ('meeting', 'Meeting'), ('task', 'Task'), ('note', 'Nota')], default='task', max_length=10)),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('data', models.DateTimeField()),
                ('durata_minuti', models.PositiveIntegerField(default=30)),
                ('completata', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='clienti.cliente')),
                ('opportunita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='opportunita.opportunita')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attivita_assegnate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attività',
                'verbose_name_plural': 'Attività',
                'ordering': ['-data'],
            },
        ),
    ]
