# Generated by Django 5.2.13 on 2026-04-24 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('valore', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stadio', models.CharField(choices=[('nuova', 'Nuova'), ('qualificata', 'Qualificata'), ('proposta', 'Proposta'), ('negoziazione', 'Negoziazione'), ('chiusa_win', 'Chiusa vinta'), ('chiusa_lost', 'Chiusa persa')], default='nuova', max_length=20)),
                ('probabilita', models.PositiveIntegerField(default=25, help_text='0-100')),
                ('chiusura_prevista', models.DateField(blank=True, null=True)),
                ('ingresso_stadio', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunita', to='clienti.cliente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunita_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunità',
                'verbose_name_plural': 'Opportunità',
                'ordering': ['-updated_at'],
            },
        ),
    ]
