# Generated by Django 5.2.13 on 2026-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunita',
            options={'ordering': ['ordine', '-updated_at'], 'verbose_name': 'Opportunità', 'verbose_name_plural': 'Opportunità'},
        ),
        migrations.AddField(
            model_name='opportunita',
            name='ordine',
            field=models.PositiveIntegerField(default=0, help_text='Posizione nella colonna Kanban (più basso = più in alto)'),
        ),
    ]
