# Generated by Django 5.2.13 on 2026-04-24 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('amministratore', 'Amministratore'), ('account_manager', 'Account manager'), ('visualizzatore', 'Visualizzatore')], default='account_manager', max_length=20)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('invitato', 'Invitato')], default='attivo', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('iniziali', models.CharField(blank=True, max_length=4)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('ultimo_accesso', models.DateTimeField(blank=True, null=True)),
                ('tema', models.CharField(choices=[('light', 'Chiaro'), ('dark', 'Scuro')], default='light', max_length=10)),
                ('densita', models.CharField(choices=[('compact', 'Compatta'), ('normal', 'Normale'), ('comfy', 'Comoda')], default='normal', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo utente',
                'verbose_name_plural': 'Profili utenti',
            },
        ),
    ]
