# Generated by Django 5.2.13 on 2026-05-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0006_contocorrente_intestatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadenzaFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField()),
                ('tipo', models.CharField(choices=[('iva', 'IVA'), ('f24', 'F24'), ('inps', 'INPS'), ('inail', 'INAIL'), ('ires', 'IRES'), ('irap', 'IRAP'), ('enasarco', 'ENASARCO'), ('ritenute', 'Ritenute'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('descrizione', models.CharField(max_length=200)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagata', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scadenza fiscale',
                'verbose_name_plural': 'Scadenze fiscali',
                'ordering': ['data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='SpesaRicorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodicita', models.CharField(choices=[('mensile', 'Mensile'), ('bimestrale', 'Bimestrale'), ('trimestrale', 'Trimestrale'), ('quadrimestrale', 'Quadrimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], default='mensile', max_length=20)),
                ('giorno_del_mese', models.PositiveSmallIntegerField(default=1, help_text="Giorno del mese in cui cade la scadenza (1-31). Se il mese ha meno giorni, viene troncato all'ultimo.")),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_ricorrenti', to='anagrafiche.categoriacosto')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_ricorrenti', to='anagrafiche.fornitore')),
            ],
            options={
                'verbose_name': 'Spesa ricorrente',
                'verbose_name_plural': 'Spese ricorrenti',
                'ordering': ['-attiva', 'descrizione'],
            },
        ),
        migrations.CreateModel(
            name='ScadenzaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pagata', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='cashflow.spesaricorrente')),
            ],
            options={
                'verbose_name': 'Scadenza spesa ricorrente',
                'verbose_name_plural': 'Scadenze spese ricorrenti',
                'ordering': ['data_scadenza'],
                'constraints': [models.UniqueConstraint(fields=('spesa', 'data_scadenza'), name='cashflow_scadenzaspesa_unique_per_data')],
            },
        ),
    ]
