# Generated by Django 5.2.13 on 2026-05-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
        ('clienti', '0003_cliente_fatturazione_elettronica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RimborsoChilometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data della trasferta.')),
                ('partenza', models.CharField(max_length=200)),
                ('destinazione', models.CharField(max_length=200)),
                ('km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tariffa_km', models.DecimalField(decimal_places=4, help_text='Tariffa €/km (es. tabelle ACI per cilindrata).', max_digits=6)),
                ('importo', models.DecimalField(blank=True, decimal_places=2, help_text='Calcolato automaticamente come km × tariffa.', max_digits=12)),
                ('causale', models.CharField(blank=True, default='', max_length=200)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('approvato', 'Approvato'), ('pagato', 'Pagato')], default='bozza', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('allegato', models.FileField(blank=True, help_text='Foglio di viaggio o altro giustificativo.', null=True, upload_to='rimborsi_km/')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amministratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rimborsi_chilometrici', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente/commessa di riferimento (facoltativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rimborsi_chilometrici', to='clienti.cliente')),
            ],
            options={
                'verbose_name': 'Rimborso chilometrico',
                'verbose_name_plural': 'Rimborsi chilometrici',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
