# Generated by Django 5.2.13 on 2026-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_rimborsochilometrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='rimborsochilometrico',
            name='is_riepilogo_mensile',
            field=models.BooleanField(default=False, help_text="Se attivo, è un totale mensile forfettario: partenza/destinazione/km/tariffa non sono richiesti e l'importo è inserito manualmente."),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='data',
            field=models.DateField(help_text='Data della trasferta o mese di riferimento.'),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='destinazione',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calcolato come km × tariffa, oppure inserito manualmente per i riepiloghi mensili.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='partenza',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rimborsochilometrico',
            name='tariffa_km',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tariffa €/km (es. tabelle ACI per cilindrata).', max_digits=6, null=True),
        ),
    ]
