# Generated by Django 5.2.13 on 2026-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testatafattura',
            name='sezionale',
            field=models.CharField(blank=True, default='', help_text="Sezionale di numerazione (es. 'A' per immediate, 'B' per differite). Lasciare vuoto per progressivo unico.", max_length=10),
        ),
        migrations.AddField(
            model_name='testatanotacredito',
            name='sezionale',
            field=models.CharField(blank=True, default='', help_text='Sezionale di numerazione (separato dalle fatture).', max_length=10),
        ),
    ]
