# Generated by Django 5.2.13 on 2026-04-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0002_testatafattura_sezionale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testatafattura',
            name='sdi_data_invio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testatafattura',
            name='sdi_id_trasmissione',
            field=models.CharField(blank=True, default='', help_text='ID trasmissione assegnato dal SDI (ricevuta RC).', max_length=80),
        ),
        migrations.AddField(
            model_name='testatafattura',
            name='sdi_stato',
            field=models.CharField(choices=[('non_inviata', 'Non inviata'), ('inviata', 'Inviata'), ('ricevuta_sdi', 'Ricevuta dal SDI'), ('accettata', 'Accettata (consegnata al destinatario)'), ('scartata', 'Scartata'), ('mancata_consegna', 'Mancata consegna (in giacenza)')], default='non_inviata', max_length=20),
        ),
        migrations.AddField(
            model_name='testatafattura',
            name='sdi_ultimo_messaggio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MessaggioSdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('invio', 'Invio (uscita verso SDI)'), ('RC', 'RC - Ricevuta consegna'), ('NS', 'NS - Notifica scarto'), ('MC', 'MC - Mancata consegna'), ('NE', 'NE - Notifica esito'), ('DT', 'DT - Decorrenza termini'), ('AT', 'AT - Attestazione trasmissione'), ('altro', 'Altro / non classificato')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_trasmissione', models.CharField(blank=True, default='', max_length=80)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.TextField(blank=True, default='', help_text='Body XML / raw del messaggio (notifica SDI o invio).')),
                ('direzione', models.CharField(choices=[('out', 'Uscita'), ('in', 'Ingresso')], default='in', max_length=10)),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_sdi', to='documenti.testatafattura')),
            ],
            options={
                'verbose_name': 'Messaggio SDI',
                'verbose_name_plural': 'Messaggi SDI',
                'ordering': ['-timestamp'],
            },
        ),
    ]
