# Generated by Django 5.2.13 on 2026-04-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0002_settore_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('attiva', models.BooleanField(default=True)),
                ('ordinamento', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria costo',
                'verbose_name_plural': 'Categorie costo',
                'ordering': ['ordinamento', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='EsigibilitaIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('I', 'Esigibilità immediata'), ('D', 'Esigibilità differita'), ('S', 'Scissione dei pagamenti')], default='I', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Esigibilità Iva',
            },
        ),
        migrations.CreateModel(
            name='FatturazioneElettronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdi', models.CharField(blank=True, default='0000000', max_length=7)),
                ('pec', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Fatturazione elettronica',
                'verbose_name_plural': 'Fatturazione elettronica',
            },
        ),
        migrations.CreateModel(
            name='FormePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('conto_corrente_cliente', models.BooleanField(default=False)),
                ('modalita_pagamento', models.CharField(choices=[('MP01', 'Contanti'), ('MP02', 'Assegno'), ('MP03', 'Assegno circolare'), ('MP04', 'Contanti presso tesoreria'), ('MP05', 'Bonifico'), ('MP06', 'Vaglia cambiario'), ('MP07', 'Bollettino bancario'), ('MP08', 'Carta di credito'), ('MP09', 'RID'), ('MP10', 'RID utenze'), ('MP11', 'RID veloce'), ('MP12', 'Riba'), ('MP13', 'MAV'), ('MP14', 'Quietanza erario'), ('MP15', 'Giroconto contabilità speciale'), ('MP16', 'Domiciliazione bancaria'), ('MP17', 'Domiciliazione postale')], default='MP05', max_length=50)),
            ],
            options={
                'verbose_name': 'Forma di pagamento',
                'verbose_name_plural': 'Forme di pagamento',
            },
        ),
        migrations.CreateModel(
            name='PosizioneIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('esigibilita_iva', models.CharField(choices=[('I', 'Esigibilità immediata'), ('D', 'Esigibilità differita'), ('S', 'Scissione dei pagamenti')], default='I', max_length=1)),
                ('scissione_pagamenti', models.BooleanField(default=False)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('bollo', models.BooleanField(default=False)),
                ('esente', models.BooleanField(default=False)),
                ('natura', models.CharField(blank=True, choices=[('', 'Standard (nessuna natura)'), ('N1', 'N1 - Escluse ex art. 15'), ('N2.1', 'N2.1 - Non soggette art. 7 lett. a)'), ('N2.2', 'N2.2 - Non soggette art. 7 lett. b)'), ('N3.1', 'N3.1 - Non imponibili esportazioni'), ('N3.2', 'N3.2 - Non imponibili cessioni intracomunitarie'), ('N3.3', 'N3.3 - Non imponibili cessioni San Marino'), ('N3.4', 'N3.4 - Non imponibili operazioni assimilate a esportazione'), ('N3.5', 'N3.5 - Non imponibili acquisti intracomunitari'), ('N3.6', 'N3.6 - Non imponibili importazioni'), ('N4', 'N4 - Esenti'), ('N5', 'N5 - Regime del margine / IVA non esposta'), ('N6.1', 'N6.1 - Reverse charge rottami'), ('N6.2', 'N6.2 - Reverse charge oro e argento'), ('N6.3', 'N6.3 - Reverse charge subappalto edile'), ('N6.4', 'N6.4 - Reverse charge cessione fabbricati'), ('N6.5', 'N6.5 - Reverse charge telefoni cellulari'), ('N6.6', 'N6.6 - Reverse charge prodotti elettronici'), ('N6.7', 'N6.7 - Reverse charge prestazioni settore edile'), ('N6.8', 'N6.8 - Reverse charge settore energetico'), ('N6.9', 'N6.9 - Reverse charge altri casi'), ('N7', "N7 - IVA assolta all'estero")], default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Posizione IVA',
                'verbose_name_plural': 'Posizioni IVA',
                'ordering': ['aliquota', 'descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Referente',
            fields=[
                ('numero', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('cognome', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Referenti',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(default='', max_length=255)),
                ('indirizzo_legale', models.CharField(default='', max_length=255)),
                ('comune_legale', models.CharField(default='', max_length=50)),
                ('cap_legale', models.CharField(default='', max_length=5)),
                ('prov_legale', models.CharField(choices=[('AG', 'Agrigento'), ('AL', 'Alessandria'), ('AN', 'Ancona'), ('AO', "Valle d'Aosta"), ('AP', 'Ascoli Piceno'), ('AQ', "L'Aquila"), ('AR', 'Arezzo'), ('AT', 'Asti'), ('AV', 'Avellino'), ('BA', 'Bari'), ('BG', 'Bergamo'), ('BI', 'Biella'), ('BL', 'Belluno'), ('BN', 'Benevento'), ('BO', 'Bologna'), ('BR', 'Brindisi'), ('BS', 'Brescia'), ('BT', 'Barletta-Andria-Trani'), ('BZ', 'Bolzano'), ('CA', 'Cagliari'), ('CB', 'Campobasso'), ('CE', 'Caserta'), ('CH', 'Chieti'), ('CL', 'Caltanissetta'), ('CN', 'Cuneo'), ('CO', 'Como'), ('CR', 'Cremona'), ('CS', 'Cosenza'), ('CT', 'Catania'), ('CZ', 'Catanzaro'), ('EN', 'Enna'), ('FC', 'Forlì-Cesena'), ('FE', 'Ferrara'), ('FG', 'Foggia'), ('FI', 'Firenze'), ('FM', 'Fermo'), ('FR', 'Frosinone'), ('GE', 'Genova'), ('GO', 'Gorizia'), ('GR', 'Grosseto'), ('IM', 'Imperia'), ('IS', 'Isernia'), ('KR', 'Crotone'), ('LC', 'Lecco'), ('LE', 'Lecce'), ('LI', 'Livorno'), ('LO', 'Lodi'), ('LT', 'Latina'), ('LU', 'Lucca'), ('MB', 'Monza e della Brianza'), ('MC', 'Macerata'), ('ME', 'Messina'), ('MI', 'Milano'), ('MN', 'Mantova'), ('MO', 'Modena'), ('MS', 'Massa-Carrara'), ('MT', 'Matera'), ('NA', 'Napoli'), ('NO', 'Novara'), ('NU', 'Nuoro'), ('OR', 'Oristano'), ('PA', 'Palermo'), ('PC', 'Piacenza'), ('PD', 'Padova'), ('PE', 'Pescara'), ('PG', 'Perugia'), ('PI', 'Pisa'), ('PN', 'Pordenone'), ('PO', 'Prato'), ('PR', 'Parma'), ('PT', 'Pistoia'), ('PU', 'Pesaro e Urbino'), ('PV', 'Pavia'), ('PZ', 'Potenza'), ('RA', 'Ravenna'), ('RC', 'Reggio Calabria'), ('RE', 'Reggio Emilia'), ('RG', 'Ragusa'), ('RI', 'Rieti'), ('RM', 'Roma'), ('RN', 'Rimini'), ('RO', 'Rovigo'), ('SA', 'Salerno'), ('SI', 'Siena'), ('SO', 'Sondrio'), ('SP', 'La Spezia'), ('SR', 'Siracusa'), ('SS', 'Sassari'), ('SU', 'Sud Sardegna'), ('SV', 'Savona'), ('TA', 'Taranto'), ('TE', 'Teramo'), ('TN', 'Trento'), ('TO', 'Torino'), ('TP', 'Trapani'), ('TR', 'Terni'), ('TS', 'Trieste'), ('TV', 'Treviso'), ('UD', 'Udine'), ('VA', 'Varese'), ('VB', 'Verbano-Cusio-Ossola'), ('VC', 'Vercelli'), ('VE', 'Venezia'), ('VI', 'Vicenza'), ('VR', 'Verona'), ('VT', 'Viterbo'), ('VV', 'Vibo Valentia')], default='', max_length=3)),
                ('indirizzo_op', models.CharField(blank=True, default='', max_length=255)),
                ('comune_op', models.CharField(blank=True, default='', max_length=50)),
                ('cap_op', models.CharField(blank=True, default='', max_length=5)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('partita_iva', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='anagrafica/')),
                ('intestazione_documenti', models.CharField(blank=True, max_length=255, null=True)),
                ('contenuto_footer', models.TextField(blank=True, null=True)),
                ('modulo_magazzino_attivo', models.BooleanField(default=True, help_text="Se disattivato, i documenti non generano movimenti di carico/scarico e la voce 'Magazzino' viene nascosta dal menu.")),
                ('fatturazione_elettronica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.fatturazioneelettronica')),
            ],
            options={
                'verbose_name': 'Anagrafica azienda',
                'verbose_name_plural': 'Anagrafiche azienda',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cognome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('provvigione_default', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fatturazione_elettronica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.fatturazioneelettronica')),
            ],
            options={
                'verbose_name_plural': 'Agenti',
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cognome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('fatturazione_elettronica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.fatturazioneelettronica')),
            ],
            options={
                'verbose_name_plural': 'Fornitori',
                'ordering': [models.Case(models.When(cognome__isnull=True, then=models.Value(1)), default=models.Value(0)), models.Case(models.When(cognome='', then=models.Value(1)), default=models.Value(0)), 'cognome', models.Case(models.When(ragione_sociale__isnull=True, then=models.Value(1)), default=models.Value(0)), models.Case(models.When(ragione_sociale='', then=models.Value(1)), default=models.Value(0)), 'ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='ContoCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca', models.CharField(blank=True, default='', max_length=150)),
                ('iban', models.CharField(default='', max_length=27)),
                ('bic_swift', models.CharField(blank=True, default='', max_length=11)),
                ('default', models.BooleanField(default=False)),
                ('anagrafica_azienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conti_correnti', to='anagrafiche.anagraficaazienda')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conti_correnti', to='clienti.cliente')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conti_correnti', to='anagrafiche.fornitore')),
            ],
            options={
                'verbose_name': 'Conto corrente',
                'verbose_name_plural': 'Conti correnti',
            },
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('cap', models.CharField(blank=True, max_length=5, null=True)),
                ('comune', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, choices=[('AG', 'Agrigento'), ('AL', 'Alessandria'), ('AN', 'Ancona'), ('AO', "Valle d'Aosta"), ('AP', 'Ascoli Piceno'), ('AQ', "L'Aquila"), ('AR', 'Arezzo'), ('AT', 'Asti'), ('AV', 'Avellino'), ('BA', 'Bari'), ('BG', 'Bergamo'), ('BI', 'Biella'), ('BL', 'Belluno'), ('BN', 'Benevento'), ('BO', 'Bologna'), ('BR', 'Brindisi'), ('BS', 'Brescia'), ('BT', 'Barletta-Andria-Trani'), ('BZ', 'Bolzano'), ('CA', 'Cagliari'), ('CB', 'Campobasso'), ('CE', 'Caserta'), ('CH', 'Chieti'), ('CL', 'Caltanissetta'), ('CN', 'Cuneo'), ('CO', 'Como'), ('CR', 'Cremona'), ('CS', 'Cosenza'), ('CT', 'Catania'), ('CZ', 'Catanzaro'), ('EN', 'Enna'), ('FC', 'Forlì-Cesena'), ('FE', 'Ferrara'), ('FG', 'Foggia'), ('FI', 'Firenze'), ('FM', 'Fermo'), ('FR', 'Frosinone'), ('GE', 'Genova'), ('GO', 'Gorizia'), ('GR', 'Grosseto'), ('IM', 'Imperia'), ('IS', 'Isernia'), ('KR', 'Crotone'), ('LC', 'Lecco'), ('LE', 'Lecce'), ('LI', 'Livorno'), ('LO', 'Lodi'), ('LT', 'Latina'), ('LU', 'Lucca'), ('MB', 'Monza e della Brianza'), ('MC', 'Macerata'), ('ME', 'Messina'), ('MI', 'Milano'), ('MN', 'Mantova'), ('MO', 'Modena'), ('MS', 'Massa-Carrara'), ('MT', 'Matera'), ('NA', 'Napoli'), ('NO', 'Novara'), ('NU', 'Nuoro'), ('OR', 'Oristano'), ('PA', 'Palermo'), ('PC', 'Piacenza'), ('PD', 'Padova'), ('PE', 'Pescara'), ('PG', 'Perugia'), ('PI', 'Pisa'), ('PN', 'Pordenone'), ('PO', 'Prato'), ('PR', 'Parma'), ('PT', 'Pistoia'), ('PU', 'Pesaro e Urbino'), ('PV', 'Pavia'), ('PZ', 'Potenza'), ('RA', 'Ravenna'), ('RC', 'Reggio Calabria'), ('RE', 'Reggio Emilia'), ('RG', 'Ragusa'), ('RI', 'Rieti'), ('RM', 'Roma'), ('RN', 'Rimini'), ('RO', 'Rovigo'), ('SA', 'Salerno'), ('SI', 'Siena'), ('SO', 'Sondrio'), ('SP', 'La Spezia'), ('SR', 'Siracusa'), ('SS', 'Sassari'), ('SU', 'Sud Sardegna'), ('SV', 'Savona'), ('TA', 'Taranto'), ('TE', 'Teramo'), ('TN', 'Trento'), ('TO', 'Torino'), ('TP', 'Trapani'), ('TR', 'Terni'), ('TS', 'Trieste'), ('TV', 'Treviso'), ('UD', 'Udine'), ('VA', 'Varese'), ('VB', 'Verbano-Cusio-Ossola'), ('VC', 'Vercelli'), ('VE', 'Venezia'), ('VI', 'Vicenza'), ('VR', 'Verona'), ('VT', 'Viterbo'), ('VV', 'Vibo Valentia')], max_length=3, null=True)),
                ('nazione', models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaigian'), ('BS', 'Bahamas'), ('BH', 'Bahrein'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Bielorussia'), ('BE', 'Belgio'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', 'Bosnia ed Erzegovina'), ('BW', 'Botswana'), ('BR', 'Brasile'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambogia'), ('CM', 'Camerun'), ('CA', 'Canada'), ('CV', 'Capo Verde'), ('TD', 'Ciad'), ('CL', 'Cile'), ('CN', 'Cina'), ('CO', 'Colombia'), ('KM', 'Comore'), ('CG', 'Congo'), ('CD', 'Congo (Repubblica Democratica)'), ('CR', 'Costa Rica'), ('CI', "Costa d'Avorio"), ('HR', 'Croazia'), ('CU', 'Cuba'), ('CY', 'Cipro'), ('CZ', 'Repubblica Ceca'), ('DK', 'Danimarca'), ('DJ', 'Gibuti'), ('DM', 'Dominica'), ('DO', 'Repubblica Dominicana'), ('EC', 'Ecuador'), ('EG', 'Egitto'), ('SV', 'El Salvador'), ('EE', 'Estonia'), ('ET', 'Etiopia'), ('FJ', 'Figi'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germania'), ('GH', 'Ghana'), ('GR', 'Grecia'), ('GD', 'Grenada'), ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HN', 'Honduras'), ('HU', 'Ungheria'), ('IS', 'Islanda'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Irlanda'), ('IL', 'Israele'), ('IT', 'Italia'), ('JM', 'Giamaica'), ('JP', 'Giappone'), ('JO', 'Giordania'), ('KZ', 'Kazakistan'), ('KE', 'Kenya'), ('KP', 'Corea del Nord'), ('KR', 'Corea del Sud'), ('KW', 'Kuwait'), ('KG', 'Kirghizistan'), ('LA', 'Laos'), ('LV', 'Lettonia'), ('LB', 'Libano'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Lussemburgo'), ('MK', 'Macedonia del Nord'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malesia'), ('MV', 'Maldive'), ('ML', 'Mali'), ('MT', 'Malta'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MX', 'Messico'), ('MD', 'Moldavia'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MA', 'Marocco'), ('MZ', 'Mozambico'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NP', 'Nepal'), ('NL', 'Paesi Bassi'), ('NZ', 'Nuova Zelanda'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NO', 'Norvegia'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PA', 'Panama'), ('PG', 'Papua Nuova Guinea'), ('PY', 'Paraguay'), ('PE', 'Perù'), ('PH', 'Filippine'), ('PL', 'Polonia'), ('PT', 'Portogallo'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Ruanda'), ('KN', 'Saint Kitts e Nevis'), ('LC', 'Santa Lucia'), ('VC', 'Saint Vincent e Grenadine'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('SA', 'Arabia Saudita'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovacchia'), ('SI', 'Slovenia'), ('SO', 'Somalia'), ('ZA', 'Sudafrica'), ('ES', 'Spagna'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SE', 'Svezia'), ('CH', 'Svizzera'), ('SY', 'Siria'), ('TW', 'Taiwan'), ('TJ', 'Tagikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailandia'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad e Tobago'), ('TN', 'Tunisia'), ('TR', 'Turchia'), ('TM', 'Turkmenistan'), ('UG', 'Uganda'), ('UA', 'Ucraina'), ('AE', 'Emirati Arabi Uniti'), ('GB', 'Regno Unito'), ('US', 'Stati Uniti'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', 'Città del Vaticano'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('XK', 'Kosovo')], default='IT', max_length=50, null=True)),
                ('sede', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to='clienti.cliente')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to='anagrafiche.fornitore')),
            ],
            options={
                'verbose_name_plural': 'Indirizzi',
            },
        ),
        migrations.CreateModel(
            name='CassaPrevidenziale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('TC01', 'Cassa avvocati e procuratori legali'), ('TC02', 'Cassa dottori commercialisti'), ('TC03', 'Cassa geometri'), ('TC04', 'Cassa ingegneri e architetti'), ('TC05', 'Cassa del notariato'), ('TC06', 'Cassa ragionieri e periti commerciali'), ('TC07', 'ENASARCO'), ('TC08', 'ENPACL - Consulenti del lavoro'), ('TC09', 'ENPAM - Medici'), ('TC10', 'ENPAF - Farmacisti'), ('TC11', 'ENPAV - Veterinari'), ('TC12', 'ENPAIA - Impiegati agricoltura'), ('TC13', 'Fondo spedizionieri e agenzie marittime'), ('TC14', 'INPGI - Giornalisti'), ('TC15', 'ONAOSI'), ('TC16', 'CASAGIT'), ('TC17', 'EPPI - Periti industriali'), ('TC18', 'EPAP - Pluricategoriale'), ('TC19', 'ENPAB - Biologi'), ('TC20', 'ENPAPI - Infermieri'), ('TC21', 'ENPAP - Psicologi'), ('TC22', 'INPS')], default='TC01', max_length=10)),
                ('aliquota_cassa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentuale_imponibile', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('codice_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.posizioneiva')),
            ],
            options={
                'verbose_name': 'Cassa previdenziale',
                'verbose_name_plural': 'Casse previdenziali',
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default='', max_length=20)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
                ('scelta', models.CharField(blank=True, default='', max_length=30)),
                ('obsoleto', models.BooleanField(default=False)),
                ('um', models.CharField(blank=True, choices=[('PZ', 'PZ - Pezzi'), ('MQ', 'MQ - Metri quadri'), ('ML', 'ML - Metri lineari'), ('KG', 'KG - Chilogrammi'), ('LT', 'LT - Litri'), ('ORE', 'ORE'), ('N', 'N')], default='PZ', max_length=10)),
                ('prezzo_listino', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('posizione_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articoli', to='anagrafiche.posizioneiva')),
            ],
            options={
                'verbose_name_plural': 'Articoli',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='ProfiloFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_fiscale', models.CharField(choices=[('RF01', 'Ordinario'), ('RF02', 'Contribuenti minimi (L. 244/2007)'), ('RF04', 'Agricoltura e pesca (art. 34, DPR 633/72)'), ('RF05', 'Vendita sali e tabacchi'), ('RF06', 'Commercio fiammiferi'), ('RF07', 'Editoria'), ('RF08', 'Telefonia pubblica'), ('RF09', 'Documenti trasporto pubblico'), ('RF10', 'Intrattenimenti e giochi'), ('RF11', 'Agenzie di viaggio (art. 74-ter)'), ('RF12', 'Agriturismo'), ('RF13', 'Vendite a domicilio'), ('RF14', 'Rivendita beni usati / arte / antiquariato'), ('RF15', "Agenzie vendite all'asta arte"), ('RF16', 'IVA per cassa P.A.'), ('RF17', 'IVA per cassa (DL 83/2012)'), ('RF18', 'Altro'), ('RF19', 'Forfettario (L. 190/2014)')], default='RF01', max_length=5)),
                ('cassa_previdenziale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.cassaprevidenziale')),
                ('esigibilita_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.esigibilitaiva')),
            ],
            options={
                'verbose_name': 'Profilo fiscale',
                'verbose_name_plural': 'Profili fiscali',
            },
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='profilo_fiscale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.profilofiscale'),
        ),
        migrations.CreateModel(
            name='Scadenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_giorni', models.IntegerField()),
                ('percentuale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fine_mese', models.BooleanField(default=False)),
                ('numero_giorni_fm', models.IntegerField(default=0)),
                ('forme_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='anagrafiche.formepagamento')),
            ],
            options={
                'verbose_name_plural': 'Scadenze',
                'ordering': ['numero_giorni'],
            },
        ),
    ]
