# Generated by Django 5.2.13 on 2026-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_seed_iva_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficaazienda',
            name='certificato_p12',
            field=models.FileField(blank=True, help_text='File .p12/.pfx per la firma digitale PAdES dei PDF.', null=True, upload_to='certificati/'),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='certificato_password',
            field=models.CharField(blank=True, default='', help_text='Passphrase del file .p12. Lasciare vuoto se non si firmano i PDF.', max_length=255),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='firma_motivo',
            field=models.CharField(blank=True, default='Documento emesso elettronicamente', help_text="Stringa 'Reason' inserita nel sigillo PAdES.", max_length=200),
        ),
    ]
