# Generated by Django 5.2.13 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_anagraficaazienda_certificato_p12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_destinatario_sdi',
            field=models.EmailField(blank=True, default='sdi01@pec.fatturapa.it', help_text="Casella PEC del SDI per l'invio (default sdi01@pec.fatturapa.it).", max_length=254),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_imap_folder',
            field=models.CharField(blank=True, default='INBOX', help_text='Cartella IMAP da cui leggere notifiche e fatture in entrata.', max_length=100),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_imap_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_imap_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_imap_port',
            field=models.PositiveIntegerField(blank=True, default=993, null=True),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_imap_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_mittente',
            field=models.EmailField(blank=True, default='', help_text='Indirizzo PEC del mittente (FROM degli invii al SDI).', max_length=254),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_smtp_host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_smtp_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='pec_smtp_user',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='anagraficaazienda',
            name='sdi_provider',
            field=models.CharField(choices=[('disabilitato', 'Disabilitato'), ('mock', 'Mock (dev/test)'), ('pec', 'PEC SMTP/IMAP')], default='disabilitato', help_text='Backend per invio fatture al Sistema di Interscambio.', max_length=20),
        ),
    ]
