# Generated by Django 5.2.13 on 2026-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_anagraficaazienda_pec_destinatario_sdi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contocorrente',
            name='intestatario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
