# Generated by Django 5.2.13 on 2026-04-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='Etichetta (email/username) salvata anche dopo cancellazione utente', max_length=150)),
                ('azione', models.CharField(choices=[('create', 'Creato'), ('update', 'Modificato'), ('delete', 'Eliminato'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login fallito'), ('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('target_type', models.CharField(blank=True, help_text='Es. "Cliente", "Opportunita"', max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('target_label', models.CharField(blank=True, help_text="Label leggibile del target al momento dell'evento", max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['azione'], name='audit_audit_azione_fbe55d_idx'), models.Index(fields=['target_type'], name='audit_audit_target__3eb7a1_idx')],
            },
        ),
    ]
