# Generated by Django 5.2.13 on 2026-04-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0003_seed_iva_defaults'),
        ('documenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('C', 'Carico (DDT fornitore)'), ('S', 'Scarico (DDT / fattura)'), ('I', 'Impegnato (ordine)'), ('O', 'Offerto (offerta)')], max_length=1)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='anagrafiche.articolo')),
                ('riga_documento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimento', to='documenti.rigadocumento')),
            ],
            options={
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['tipo'], name='magazzino_m_tipo_20397e_idx'), models.Index(fields=['articolo'], name='magazzino_m_articol_df826a_idx')],
            },
        ),
    ]
