# Generated by Django 5.2.13 on 2026-04-24 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('colore', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warn', 'Warn'), ('danger', 'Danger'), ('neutral', 'Neutro')], default='info', max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('azienda', 'Azienda'), ('privato', 'Privato'), ('ente', 'Ente pubblico')], default='azienda', max_length=10)),
                ('settore', models.CharField(blank=True, max_length=100)),
                ('partita_iva', models.CharField(db_index=True, max_length=16, unique=True)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('codice_sdi', models.CharField(blank=True, max_length=7)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('indirizzo', models.CharField(blank=True, max_length=200)),
                ('cap', models.CharField(blank=True, max_length=5)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('nazione', models.CharField(default='IT', max_length=2)),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('prospect', 'Prospect'), ('attesa', 'In attesa'), ('inattivo', 'Inattivo')], default='prospect', max_length=10)),
                ('numero_dipendenti', models.CharField(blank=True, max_length=30)),
                ('fatturato_annuo_stimato', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('cliente_dal', models.DateField(blank=True, null=True)),
                ('ultimo_contatto', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_gestiti', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='clienti', to='clienti.tag')),
            ],
            options={
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('primary', models.BooleanField(default=False, verbose_name='Contatto principale')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='clienti.cliente')),
            ],
            options={
                'ordering': ['-primary', 'cognome', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['stato'], name='clienti_cli_stato_9c3507_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['settore'], name='clienti_cli_settore_36716a_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['citta'], name='clienti_cli_citta_ea2ac9_idx'),
        ),
    ]
