# Generated by Django 5.2.13 on 2026-04-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('clienti', '0002_settore_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fatturazione_elettronica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='anagrafiche.fatturazioneelettronica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forme_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='anagrafiche.formepagamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='posizione_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='anagrafiche.posizioneiva'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profilo_fiscale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='anagrafiche.profilofiscale'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='anagrafiche.referente'),
        ),
    ]
